name: healthdashboard
description: Demonstrates how to use the health plugin.
publish_to: "none"
version: 4.5.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  health: ^6.0.0
  flutter_background_service: ^3.0.1
  background_fetch: ^1.1.6
  fl_chart: 0.50.6
  google_fonts: 2.2.0
  percent_indicator: 4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
